polkadot-js/dev

packages/dev/config/jest.js
Default is `['**/__tests__/**/*.js?(x)', '**/?(*.)+(spec|test).js?(x)']`
=> Allow .spec.ts files

packages/dev-react/package.json, yarn.lock
webpack-plugin-serve has it's own bundled HMR, I believe this is at least part of the issue in https://github.com/polkadot-js/apps/issues/780 (Issues in there comes from this plugin, not the built-in version)
=> Remove explicit react-hot-loader

packages/dev/scripts/polkadot-dev-build-ts.sh
Hi, I am using this build script and found it won't copy the d.ts files from `./build` to `./packages/[package_name]/build` if it's using Lerna and only have one package in packages(maybe I shouldn't use lerna if I only have one package... but there are some benefits to use Lerna even if there is only one package such as for easier to extend in the future...). So I added three lines code to make this script support the case above. Please let me know if you guys don't need these code, I will just close this PR.
=>  support build when using lerna with on package

packages/dev/scripts/polkadot-dev-ghact-docs.sh
Should fix https://github.com/polkadot-js/api/issues/1655. The `gh-pages` branch is missing the `.nojekyll` file (even though `build-docs` has the `.nojekyll` file), making pages starting with `_` inaccessible.
```
Usage: gh-pages [options]
Options:
[...]
-t, --dotfiles           Include dotfiles
```
=> Include dotfiles (.nojekyll) when pushing to gh-pages

packages/dev/scripts/polkadot-dev-build-ts.js
Addresses the issue raised in https://github.com/polkadot-js/api/issues/2237
=> Copy *.hbs as part of build outputs

package.json, packages/dev/config/eslint.cjs, packages/dev/src/Component.tsx, packages/dev/src/index.ts, packages/dev/src/test1/bar.ts, packages/dev/src/test1/circ1.ts
Attempts to fix https://github.com/polkadot-js/apps/pull/4137#discussion_r537320332 
Additionally also does enforce a new line after import blocks, which helps.
=> eslint import padding

packages/dev/scripts/polkadot-dev-build-ts.mjs
Closes https://github.com/polkadot-js/dev/issues/512 (prevents https://github.com/polkadot-js/common/issues/1225)
(tested agains the problematic util-crypto branch)
```
*** @polkadot/util-crypto 7.9.1
Successfully compiled 236 files with Babel (1734ms).
Successfully compiled 236 files with Babel (855ms).
Error: util-crypto/build/base32/bs32.d.ts:: line 26:: invalid /src/ import:: 
export declare const base32Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
```
=> /src/ import linting

packages/dev/scripts/polkadot-dev-build-ts.mjs
We don't like using them, however they appear everywhere in the extension repo, so should be catered for
Needs to fix https://github.com/polkadot-js/extension/issues/945
=> Treat *.test.ts same as *.spec.ts

packages/dev/config/rollup.js
By using Universal Module Definition (UMD), the bundled file can be properly loaded for Browser, and Deno.
For more information about the bundler format, I think [this article](https://betterprogramming.pub/what-are-cjs-amd-umd-esm-system-and-iife-3633a112db62) can explain better.
Below is some information why we need this fix.
---
Currently for Deno, if we import the bundled file with IIFE format like below:
```js
import 'https://cdn.jsdelivr.net/npm/@polkadot/util@8.2.2/bundle-polkadot-util.js';
import 'https://cdn.jsdelivr.net/npm/@polkadot/util-crypto@8.2.2/bundle-polkadot-util-crypto.js';
```
It will give this error because the IIFE is not registering/expose `polkadotUtil` on the global context.
---
And if we import it like below (without using the bundled file, but immediately try …
=> Change bundle format to UMD

packages/dev/scripts/polkadot-dev-build-ts.mjs
Hi!
Vite shows EISDIR error at `new URL('.', import.meta.url)` expression on build.
Actually checking import.meta.url is not enough to fix this problem.
The problem is when bundler tries to build the code in production build, in compile time it has no idea about how the expression `new URL('.', import.meta.url)` should be resolved in runtime. And it tries to read all the file and bake it inline in base64 form. And in case of `new URL('.', ...)` it tries to read the dir what is impossible and throws compile-time error EISDIR. 
So I created a workaround code which gives the same output in Vite and Node.js environments:
```js
const filePathname = new URL(import.meta.url).pathname
const folderPathname = filePathname.substring(0, filePathname.lastIndexOf('/')+1)
```
actually does literally the …
=> Fix Vite build bundling error about EISDIR on `new URL('.', import.meta.url)`

packages/dev/config/rollup.js
Due to the fact that substrate connect is `multiple chunks` generated build, the `inlineDynamicImports` needs to be activated for it to be build correctly in a file. I preferred to avoid adding that for all bundles.
@jacogr let me know if it is preferable the option `inlineDynamicImports` to be added in all bundles.
=> Fix createBundle for substrate connect

packages/dev/config/rollup.js, packages/dev/package.json, yarn.lock
This PR adds the [Rollup dynamic variable imports](https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars) plugin. 
At [a previous ](https://github.com/polkadot-js/api/pull/5150) PR, substrate connect provider was added to the bundle of polkadotApi in order for a user to be able to use is, as `WsProvider`.
Substrate connect though [dynamically imports](https://github.com/paritytech/substrate-connect/blob/main/packages/connect/src/connector/specs/index.ts#L10) chains based on the name provided from the `WellKnownChain` enumeration. `Rollup`, by default, does not support dynamic vars, but only defined strings (see these relative issues: [1](https://github.com/rollup/rollup/issues/2463), [2](https://github.com/rollup/rollup/issues/2097). 
This plugin does exactly what it promises, …
=> Add rollup dynamic import variables plugin

packages/dev/config/rollup.js
See https://github.com/polkadot-js/extension/runs/7913032891?check_suite_focus=true
=> Fix for rollup pluginDynamicImportVars

packages/dev/package.json, yarn.lock
The semver package has circular deps which then breaks due to this https://github.com/rollup/plugins/issues/1258 
(See an example of the breakage here https://github.com/polkadot-js/common/runs/8225532412?check_suite_focus=true)
=> Downgrade rollup node resolve

packages/dev/config/tsconfig.json
As per https://github.com/polkadot-js/api/issues/5524
This should be mostly ok now in all the libs - on the end-user apps such as extension/apps there may be more elbow-grease needed to either get them working or swap them to `node`. (Here some dependencies are somewhat problematic)
=> Swap base moduleResolution to nodenext

packages/dev/config/tsconfig.json
There are some small conflicts with the typescript-eslint rules here as well (We certainly want to switch on at some point, however quite a bit more issues in polkadot-js common)
=> Disable noPropertyAccessFromIndexSignature (future)

packages/dev/scripts/polkadot-dev-build-ts.mjs
In addition to types, import & require, see e.g. https://github.com/uuidjs/uuid/pull/462 (and the linked issues through to e.g. webpack)
This may help with e.g. https://github.com/polkadot-js/api/issues/5636#issuecomment-1538191319
=> Add module key to export map

CHANGELOG.md, package.json, packages/dev-test/package.json, packages/dev-ts/package.json, packages/dev/package.json, packages/dev/scripts/polkadot-ci-ghact-build.mjs, packages/dev/scripts/util.mjs, yarn.lock
The following adds topological sorting for a workspace and it's corresponding packages. Unfortunately not all `@polkadot/*` are able to be ordered with full topological integrity as some repos have circular deps. That being said this is one avenue to help the releases be more fault tolerant and will help avoid situations like: https://github.com/polkadot-js/api/issues/5841
The current algorithm deals with circular dependencies by adding them to the end of the sorted vector. The order in which it adds them is based on the length of their vertices. This is from least to greatest. 
closes: https://github.com/polkadot-js/dev/issues/1139
=> feat: topological sort for releases

packages/dev/scripts/util.mjs
When packages have a single package topo sort will return nothing. Therefore we need to attach an edge case where length === 1 return the same `dirs`.
=> Fix topo sort for single dirs

packages/dev/scripts/util.mjs
When packages have no edges they should still be added to the topo sort result.
=> Fix topo sort for standAlone packages

packages/dev/scripts/polkadot-dev-build-ts.mjs
rel: https://github.com/polkadot-js/dev/pull/1147
Fix an error where `./globals.d.ts` was ignored as a top level export, causing test builds to fail.
=> Fix globals.d.ts export

README.md, packages/dev/README.md
This PR aims to create docs for all the scripts used in `@polkadot/dev`. This is super important since all the polkadot-js repos use these scripts - so some sort of source of truth is useful.
=> Create docs for all the scripts in `@polkadot/dev`

packages/dev/scripts/polkadot-dev-build-ts.mjs
Introduced in deno v2, the Buffer type is no longer part of global. This has extended in our CI to the 1.x versions as well (I really don't know why after hours of looking). To solve this wherever the type is used in the deno build we adjust the imports to include the Buffer import from `node:buffer` specifically. This will solve our build issues we currently have in all our CI's, and should allow us to update our deno ci builds to lts
=> Write the Buffer Import to necessary Deno build files

packages/dev/scripts/polkadot-dev-build-ts.mjs
This updates the `polkadot-dev-build-ts.mjs` build script to align with the current used `ES2022` target. Specifically, this means that we no longer need to strip the private visibility of properties, since this is now natively supported.
=> build(dev): Stop removing private fields
