polkadot-js/dev

flow-typed/leveldown.js, flow-typed/levelup.js, flow-typed/libp2p-kad-dht.js, flow-typed/libp2p-mdns.js, flow-typed/libp2p-multiplex.js, flow-typed/libp2p-railing.js, flow-typed/libp2p-secio.js, flow-typed/libp2p-spdy.js, flow-typed/libp2p-tcp.js, flow-typed/libp2p-websockets.js, flow-typed/libp2p.js, flow-typed/memdown.js, flow-typed/merkle-patricia-tree.js, flow-typed/mkdirp.js, flow-typed/peer-book.js, flow-typed/peer-id.js, flow-typed/peer-info.js, flow-typed/pull-pushable.js, flow-typed/rimraf.js, flow-typed/webassembly.js, package.json, yarn.lock
Closes https://github.com/polkadot-js/dev/issues/55
=> Update flow-typed packages

.flowconfig, skeleton/flowconfig
=> Add flow lint checking

.flowconfig, skeleton/flowconfig, src/testRoot.js
Closes  https://github.com/polkadot-js/dev/issues/59
=> Add warning display for flow lint

flow-typed/co-body.js, flow-typed/deasync.js, flow-typed/koa-body.js, flow-typed/koa-json.js, flow-typed/koa-route.js, flow-typed/koa-websocket.js, flow-typed/pull-stream.js, flow-typed/rlp.js, flow-typed/yargs.js, package.json, src/testRoot.js, yarn.lock
Additionally, update flow-bin.
Closes https://github.com/polkadot-js/dev/pull/66
=> Add definitions from @polkadot/client

package.json, scripts/polkadot-dev-clean-branches.sh, scripts/polkadot-dev-update-deps.js, scripts/polkadot-dev-update-deps.sh
Closes https://github.com/polkadot-js/dev/issues/49
=> Added keep-up-to-date scripts

scripts/polkadot-dev-build-docs.js
=> Skip docs with .nodoc

scripts/polkadot-dev-build-babel.sh
Copy unknown files via babel.
Additionally -
Closes #96 
Closes #97
=> Copy files via babel

flow-typed/semver-compare.js
=> flow-typed for semver-compare

.travis.yml, package.json
Prevents older versions https://github.com/polkadot-js/apps/pull/78
=> Add yarn & node to engines

packages/dev/scripts/polkadot-dev-build-ts.sh
Needed to move static assets into ui
=> Copy css and svg static resources

packages/dev/scripts/polkadot-dev-build-babel.sh, packages/dev/scripts/polkadot-dev-build-docs.sh
- Closes https://github.com/polkadot-js/dev/issues/181
- Closes https://github.com/polkadot-js/dev/issues/187
=> Build docs for gh-pages (as configured)

packages/dev-react/package.json
Follow-up of https://github.com/polkadot-js/apps/pull/784
To be merged before: https://github.com/polkadot-js/apps/pull/785
=> Added react-hot-loader to 'dev-react' config

all-deps.js, all-update.sh
- Make sure all the relevant repos are in your project folder - dev, ts, wasm, common, api, ui, extension, apps, tools, client
- run ./dev/all-update.sh from the root project folder
=> Add magic update script to git

.circleci/config.yml, packages/dev/package.json, packages/dev/scripts/polkadot-dev-circleci-build.sh
The script is not great (just a copy with stuff removed, but does the trick - for now)
=> Add CircleCI

all-update.sh, packages/dev/scripts/polkadot-ci-ghact-build.js, packages/dev/scripts/polkadot-dev-version.js
Fixes issue on https://github.com/polkadot-js/api/pull/2034/commits/21c3ab49b51ed5f154ed17b6cdb83f8a996efe4a
=> Run yarn on polkadot-dev-version

packages/dev/config/eslint.js
As per https://github.com/yannickcr/eslint-plugin-react/issues/2654
=> Disable completely broken prop-types rule

packages/dev/package.json, yarn.lock
Until we have rushstack support as per https://github.com/microsoft/rushstack/issues/2310
=> Fix eslint version

packages/dev/package.json, tester.mjs, yarn.lock
As per https://github.com/polkadot-js/extension/issues/582#issuecomment-743970868
=> Remove reference to old removed lerna script

packages/dev/package.json, yarn.lock
Closes https://github.com/polkadot-js/dev/issues/441
=> Remove old vuepress exec script reference

packages/dev/config/babel-plugins.cjs, packages/dev/package.json, yarn.lock
Removal of those plugins makes it not polyfill the syntax leading to faster code
=> Remove redundant babel plugins

.gitignore, tsconfig.base.json, tsconfig.json
Split from https://github.com/polkadot-js/dev/pull/523
=> Add tsconfig.base

packages/dev/scripts/polkadot-dev-build-ts.mjs
See https://github.com/polkadot-js/api/issues/4633
=> Build step hack for upstream Vite issues

packages/dev/node/loader-ts.mjs, packages/dev/node/require-test.cjs, packages/dev/package.json, packages/dev/scripts/polkadot-dev-run-node-test.mjs, packages/dev/scripts/polkadot-dev-run-node-ts.mjs, packages/dev/scripts/util.mjs, packages/dev/src/index.spec.ts, packages/dev/src/test1/index.spec.ts, packages/dev/src/test1/index.ts, packages/dev/src/testRoot.ts, yarn.lock
After this `node:test` actually works - both react components and "normal"
=> Make node --test operational

packages/dev/src/node/test/node.d.ts
And this is why I've only been pushing existing local branch up while sick - if I try and do something, this happens...
=> Fix naming

package.json, packages/dev/config/tsconfig.json, packages/dev/package.json, packages/dev/scripts/polkadot-dev-build-ts.mjs, packages/dev/src/node/ts/loader.mjs
Pull interesting bits from https://github.com/polkadot-js/dev/pull/969
=> Pre-align tsc targets

packages/dev/scripts/polkadot-dev-build-ts.mjs
Until https://github.com/denoland/deno/issues/18557 is resolved
We have a git dep inside `@zondax/ledger-substrate`
=> Remove npm: deno specifiers

packages/dev/scripts/polkadot-dev-build-ts.mjs
See https://github.com/polkadot-js/api/pull/5617 for the rationale.
Here we just apply the replacements at time of compilation instead of tweaking all the sources from all the repos.
=> Adjust output for private fields

CHANGELOG.md, package.json, packages/dev-test/package.json, packages/dev-test/src/env/expect.ts, packages/dev-ts/package.json, packages/dev/config/eslint.js, packages/dev/config/eslint.rules.js, packages/dev/package.json, packages/dev/scripts/polkadot-ci-ghact-build.mjs, packages/dev/scripts/polkadot-dev-build-ts.mjs, packages/dev/scripts/util.mjs, scripts/all-deps.js, yarn.lock
See https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#reworked-configuration-names
=> Bump typescript eslint

packages/dev/scripts/polkadot-exec-node-test.mjs
Current Node versions doesn't quite get the spec filename correct
=> Extract filename from stack when incorrect

CHANGELOG.md, package.json, packages/dev-test/package.json, packages/dev-ts/package.json, packages/dev/package.json, packages/dev/scripts/polkadot-dev-build-ts.mjs, yarn.lock
rel: https://github.com/polkadot-js/api/issues/5711
This is a mirror of: https://github.com/polkadot-js/dev/pull/1101. All credit to the original contributor. I just added the correct version bump in this PR.
=> Duplicate .d.ts files into cjs
